export const DIMENSIONS = {
  1: {
    height: 60,
    width: 150,
  },
  2: {
    height: 60,
    width: 300,
  },
  3: {
    height: 90,
    width: 300,
  },
  4: {
    height: 90,
    width: 450,
  },
};

export const ALL_BANNERS = {
  1: [
    {
      index:1,
      text: "請在對話框裡輸入你想要的文字",
      fontRatio: 85,
      top:30,
      styles: {
        "font-size": "80px",
        "font-family":"cwTeXKai-zhonly",
        "margin-top": "0rem",
        "text-align":"center",
        "line-height":"1",
        color: "rgb(234.02 229.29 229.29 / 1)",
      },
    },
    
  ],
  2: [
    {
      index:1,
      text: "請在對話框裡輸入你想要的文字",
      fontRatio: 75,
      top:10,
      styles: {
        "font-size": "80px",
        "margin-top": "0rem",
        "font-family":"cwTeXKai-zhonly",
        "text-align":"center",
        "line-height":"1",
        color: "rgb(234.02 229.29 229.29 / 1)",
      },
    },
    {
      index:2,
      text: "請在對話框裡輸入你想要的文字",
      fontRatio: 150,
      top:51,
      styles: {
        "font-size": "80px",
        "margin-top": "0rem",
        "font-family":"cwTeXKai-zhonly",
        "text-align":"center",
        "line-height":"1",
        color: "rgb(234.02 229.29 229.29 / 1)",
      },
    },
  ],
  3: [
    {
      index:1,
      text: "請在對話框裡輸入你想要的文字",
      fontRatio: 150,
      top:3,
      styles: {
        "font-size": "80px",
        "margin-top": "0px",
        "font-family":"cwTeXKai-zhonly",
        "text-align":"center",
        "line-height":"1",
        color: "rgb(234.02 229.29 229.29 / 1)",
      },
    },
    {
      index:2,
      text: "請在對話框裡輸入你想要的文字",
      fontRatio: 60,
      top:30,
      styles: {
        "font-size": "80px",
        "margin-top": "0px",
        "font-family":"cwTeXKai-zhonly",
        "text-align":"center",
        "line-height":"1",
        color: "rgb(234.02 229.29 229.29 / 1)",
      },
    },
    {
      index:3,
      text: "請在對話框裡輸入你想要的文字",
      fontRatio: 150,
      top:80,
      styles: {
        "font-size": "80px",
        "font-family":"cwTeXKai-zhonly",
        "text-align":"center",
        "margin-top": "0px",
        "line-height":"1",
        color: "rgb(234.02 229.29 229.29 / 1)",
      },
    },
  ],
  // {
  //   text:"請在對話框裡輸入你想要的文字",
  //   fontSize:'23px',
  //   styles:{
  //     'font-size':'80px',
  //     'margin-top':"100px"
  //   }
  // },
  // {
  //   text:"請在對話框裡輸入你想要的文字",
  //   fontSize:'23px',
  //   styles:{
  //     'font-size':'80px',
  //     'margin-top':"10px"
  //   }
  // }
};

export const BANNERS = {
  1: {
    version: "5.3.0",
    objects: [
      {
        type: "rect",
        version: "5.3.0",
        originX: "left",
        originY: "top",
        left: -0.5,
        top: -0.5,
        width: 1100,
        height: 440,
        fill: "#eb4165ff",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        rx: 0,
        ry: 0,
        selectable: false,
        hasControls: true,
      },
      {
        type: "textbox",
        version: "5.3.0",
        originX: "left",
        originY: "top",
        left: 25,
        top: 166,
        width: 1069.6,
        height: 90.4,
        fill: "white",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        fontFamily: "Noto",
        fontWeight: "normal",
        fontSize: 80,
        text: "請在對話框裡輸入你想要的文字",
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "center",
        fontStyle: "normal",
        lineHeight: 1.16,
        textBackgroundColor: "",
        charSpacing: 0,
        styles: [],
        direction: "ltr",
        path: null,
        pathStartOffset: 0,
        pathSide: "left",
        pathAlign: "baseline",
        minWidth: 20,
        splitByGrapheme: false,
        selectable: true,
        hasControls: true,
      },
    ],
    canvas: {
      height: 440,
      width: 1100,
    },
  },
  2: {
    version: "5.3.0",
    objects: [
      {
        type: "rect",
        version: "5.3.0",
        originX: "left",
        originY: "top",
        left: -0.5,
        top: -0.5,
        width: 1100,
        height: 440,
        fill: "#9c28b1ff",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        rx: 0,
        ry: 0,
        selectable: false,
        hasControls: true,
      },
      {
        type: "textbox",
        version: "5.3.0",
        originX: "left",
        originY: "top",
        left: 21,
        top: 78,
        width: 1069.6,
        height: 113,
        fill: "white",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        fontFamily: "Noto",
        fontWeight: "normal",
        fontSize: 100,
        text: "請在對話框裡輸入你想要的文字",
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "center",
        fontStyle: "normal",
        lineHeight: 1.16,
        textBackgroundColor: "",
        charSpacing: 0,
        styles: [],
        direction: "ltr",
        path: null,
        pathStartOffset: 0,
        pathSide: "left",
        pathAlign: "baseline",
        minWidth: 20,
        splitByGrapheme: false,
        selectable: true,
        hasControls: true,
      },
      {
        type: "textbox",
        version: "5.3.0",
        originX: "left",
        originY: "top",
        left: 34,
        top: 199,
        width: 1040,
        height: 55.37,
        fill: "white",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        fontFamily: "Noto",
        fontWeight: "normal",
        fontSize: 49,
        text: "請在對話框裡輸入你想要的文字",
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "center",
        fontStyle: "normal",
        lineHeight: 1.16,
        textBackgroundColor: "",
        charSpacing: 0,
        styles: [],
        direction: "ltr",
        path: null,
        pathStartOffset: 0,
        pathSide: "left",
        pathAlign: "baseline",
        minWidth: 20,
        splitByGrapheme: false,
        selectable: true,
        hasControls: true,
      },
    ],
    canvas: {
      height: 330,
      width: 1100,
    },
  },
  3: {
    version: "5.3.0",
    objects: [
      {
        type: "rect",
        version: "5.3.0",
        originX: "left",
        originY: "top",
        left: -0.5,
        top: -0.5,
        width: 1100,
        height: 440,
        fill: "#eb1d4eff",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        rx: 0,
        ry: 0,
        selectable: false,
        hasControls: true,
      },
      {
        type: "textbox",
        version: "5.3.0",
        originX: "left",
        originY: "top",
        left: 21.05,
        top: 106.56,
        width: 1069.6,
        height: 124.3,
        fill: "white",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        fontFamily: "Noto",
        fontWeight: "normal",
        fontSize: 110,
        text: "請在對話框裡輸入你想要的文字",
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "center",
        fontStyle: "normal",
        lineHeight: 1.16,
        textBackgroundColor: "",
        charSpacing: 0,
        styles: [],
        direction: "ltr",
        path: null,
        pathStartOffset: 0,
        pathSide: "left",
        pathAlign: "baseline",
        minWidth: 20,
        splitByGrapheme: false,
        selectable: true,
        hasControls: true,
      },
      {
        type: "textbox",
        version: "5.3.0",
        originX: "left",
        originY: "top",
        left: 29,
        top: 236,
        width: 1040,
        height: 62.15,
        fill: "#353535ff",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        fontFamily: "Noto",
        fontSize: 55,
        text: "請在對話框裡輸入你想要的文字",
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "center",
        fontStyle: "normal",
        lineHeight: 1.16,
        textBackgroundColor: "",
        charSpacing: 0,
        styles: [],
        direction: "ltr",
        path: null,
        pathStartOffset: 0,
        pathSide: "left",
        pathAlign: "baseline",
        minWidth: 20,
        splitByGrapheme: false,
        selectable: true,
        hasControls: true,
      },
      {
        type: "textbox",
        version: "5.3.0",
        originX: "left",
        originY: "top",
        left: 48,
        top: 32,
        width: 1040,
        height: 62.15,
        fill: "white",
        stroke: null,
        strokeWidth: 1,
        strokeDashArray: null,
        strokeLineCap: "butt",
        strokeDashOffset: 0,
        strokeLineJoin: "miter",
        strokeUniform: false,
        strokeMiterLimit: 4,
        scaleX: 1,
        scaleY: 1,
        angle: 0,
        flipX: false,
        flipY: false,
        opacity: 1,
        shadow: null,
        visible: true,
        backgroundColor: "",
        fillRule: "nonzero",
        paintFirst: "fill",
        globalCompositeOperation: "source-over",
        skewX: 0,
        skewY: 0,
        fontFamily: "Noto",
        fontWeight: "normal",
        fontSize: 55,
        text: "請在對話框裡輸入你想要的文字",
        underline: false,
        overline: false,
        linethrough: false,
        textAlign: "center",
        fontStyle: "normal",
        lineHeight: 1.16,
        textBackgroundColor: "",
        charSpacing: 0,
        styles: [],
        direction: "ltr",
        path: null,
        pathStartOffset: 0,
        pathSide: "left",
        pathAlign: "baseline",
        minWidth: 20,
        splitByGrapheme: false,
        selectable: true,
        hasControls: true,
      },
    ],
    canvas: {
      height: 330,
      width: 1100,
    },
  },
};
